"""
Part of RedELK

Regression guard for the ATT&CK dictionary's tactic taxonomy (bug #4).

The dictionary (elkserver/.../data/attack/enterprise-attack.json) is generated by
tools/generate_attack_dictionary.py, whose collect_tactics copies tactic names verbatim from the
STIX bundle it downloads - it has no rename table, so whatever tactic taxonomy the *source* carries
is what ships. The source therefore has to be pinned, or the taxonomy silently drifts. It once did:
b1d7a73 generated from the generator's *unpinned* DEFAULT_URL (enterprise-attack/enterprise-attack.json,
which floats to the latest release), so an ATT&CK v19 bundle landed unnoticed - v19 renamed TA0005
"Defense Evasion" to "Stealth" and split out a new tactic TA0112 "Defense Impairment".

RedELK now deliberately tracks ATT&CK Enterprise v19.2: the generator's DEFAULT_URL is pinned to
enterprise-attack-19.2.json, so "Stealth" and "Defense Impairment" are the *expected*, official
names here - not corruption. This guard pins the two things that must move together with that
choice: the release the shipped dict was built from, and the exact tactic set it may reference. A
regeneration from a different (bumped, reverted, or accidentally floating) source changes one or
both and fails CI, instead of silently relabelling the ATT&CK dashboard.

To bump ATT&CK: edit DEFAULT_URL in tools/generate_attack_dictionary.py, regenerate, then update
EXPECTED_ATTACK_VERSION and CANONICAL_TACTICS below to match - deliberately, in the same change.

Deliberately free of pytest fixtures and of any `import conftest` (conftest imports pytest and
yaml at module scope): the module is importable and runnable on a bare interpreter, so it can be
executed standalone the way the connector suites are.

Authors:
- RedELK contributors
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

SHIPPED_DICTIONARY = (
    REPO_ROOT
    / "elkserver"
    / "docker"
    / "redelk-base"
    / "redelkinstalldata"
    / "data"
    / "attack"
    / "enterprise-attack.json"
)

# The ATT&CK Enterprise release the dictionary is pinned to. Must match the version generated from
# DEFAULT_URL in tools/generate_attack_dictionary.py. Bump both together, deliberately.
EXPECTED_ATTACK_VERSION = "19.2"

# The canonical MITRE ATT&CK *Enterprise* tactics for EXPECTED_ATTACK_VERSION, id -> name. v19
# renamed TA0005 Defense Evasion -> "Stealth" and added TA0112 "Defense Impairment", so this is a
# 15-tactic set. It is a closed set for a given release: if a genuine ATT&CK bump adds or renames a
# tactic, update this table *and* EXPECTED_ATTACK_VERSION together - a failure here means either
# that happened or the dictionary was regenerated from a different source, and the two must not be
# confused.
CANONICAL_TACTICS: dict[str, str] = {
    "TA0043": "Reconnaissance",
    "TA0042": "Resource Development",
    "TA0001": "Initial Access",
    "TA0002": "Execution",
    "TA0003": "Persistence",
    "TA0004": "Privilege Escalation",
    "TA0005": "Stealth",
    "TA0006": "Credential Access",
    "TA0007": "Discovery",
    "TA0008": "Lateral Movement",
    "TA0009": "Collection",
    "TA0011": "Command and Control",
    "TA0010": "Exfiltration",
    "TA0040": "Impact",
    "TA0112": "Defense Impairment",
}


def _load_dictionary(path: Path | str = SHIPPED_DICTIONARY) -> dict:
    with Path(path).open(encoding="utf-8") as handle:
        return json.load(handle)


def _tactic_entries(dictionary: dict):
    """Yield (technique_id, tactic_object) for every tactic referenced by every technique."""
    for technique_id, info in dictionary.get("techniques", {}).items():
        for tactic in info.get("tactics", []):
            yield technique_id, tactic


def _non_canonical_tactics(dictionary: dict) -> list[str]:
    """Return a sorted, de-duplicated list of reasons the dict's tactics are not canonical."""
    domain = dictionary.get("domain")
    if domain != "enterprise-attack":
        # CANONICAL_TACTICS only describes the Enterprise domain; refuse to judge anything else
        # rather than drowning the caller in "unknown tactic" noise from mobile/ICS.
        return [f"dictionary domain is {domain!r}, expected 'enterprise-attack'"]

    offenders: set[str] = set()
    for technique_id, tactic in _tactic_entries(dictionary):
        tid = tactic.get("id")
        name = tactic.get("name")
        reference = tactic.get("reference")

        expected_name = CANONICAL_TACTICS.get(tid)
        if expected_name is None:
            offenders.add(
                f"{technique_id}: {tid!r} ({name!r}) is not a canonical Enterprise tactic"
            )
            continue
        if name != expected_name:
            offenders.add(
                f"{technique_id}: tactic {tid} is named {name!r}, canonical name is "
                f"{expected_name!r}"
            )
        expected_reference = f"https://attack.mitre.org/tactics/{tid}/"
        if reference != expected_reference:
            offenders.add(
                f"{technique_id}: tactic {tid} reference is {reference!r}, expected "
                f"{expected_reference!r}"
            )
    return sorted(offenders)


def test_dictionary_tracks_the_pinned_release():
    """The shipped dict must be the ATT&CK release we pinned, so its taxonomy is the one we vetted.

    If this fails, generate_attack_dictionary.py was run against a different source than
    EXPECTED_ATTACK_VERSION (a floating DEFAULT_URL, a bump, or a revert) - reconcile the pin, the
    regenerated dict and this constant deliberately.
    """
    version = _load_dictionary().get("version")
    assert version == EXPECTED_ATTACK_VERSION, (
        f"shipped ATT&CK dictionary is v{version!r}, expected v{EXPECTED_ATTACK_VERSION!r}; "
        "the generator's DEFAULT_URL and this test must be bumped together"
    )


def test_shipped_dictionary_uses_only_canonical_tactics():
    """Every tactic id/name/reference in the shipped dict must be a real Enterprise tactic.

    Catches a source drift that changes the tactic taxonomy - e.g. TA0005's name or the presence
    of TA0112 - which would silently relabel the ATT&CK dashboard.
    """
    offenders = _non_canonical_tactics(_load_dictionary())

    assert not offenders, (
        "the shipped ATT&CK dictionary contains tactics outside the pinned "
        f"v{EXPECTED_ATTACK_VERSION} set:\n  "
        + "\n  ".join(offenders)
        + "\n\nIf a genuine MITRE release changed the Enterprise tactic set, update "
        "CANONICAL_TACTICS and EXPECTED_ATTACK_VERSION deliberately. Otherwise the dictionary was "
        "regenerated from a different source - see this file's docstring and commit b1d7a73."
    )


if __name__ == "__main__":
    # The repo venv has no pytest; this mirrors the connector suites' standalone convention so the
    # guard can be run as `python3 test_attack_dictionary_tactics_canonical.py`.
    _checks = [
        ("dictionary_tracks_the_pinned_release", test_dictionary_tracks_the_pinned_release),
        ("shipped_dictionary_uses_only_canonical_tactics", test_shipped_dictionary_uses_only_canonical_tactics),
    ]
    _failures = 0
    for _name, _check in _checks:
        try:
            _check()
        except AssertionError as exc:
            _failures += 1
            print(f"FAIL {_name}: {exc}")
        else:
            print(f"PASS {_name}")
    sys.exit(1 if _failures else 0)
