#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""
Part of RedELK

This alarm always triggers. Only use for testing purposes.

Authors:
- Lorenzo Bernardi (@fastlorenzo)
- RedELK contributors
"""

import logging

from modules.helpers import get_initial_alarm_result, get_query

info = {
    "version": 0.2,
    "name": "dummy alarm",
    "alarmmsg": "ALARM GENERATED BY DUMMY",
    "description": "This alarm always triggers. Only use for testing purposes.",
    "type": "redelk_alarm",
    "submodule": "alarm_dummy",
}


class Module:
    """dummy alarm module
    This check returns the last IOC in rtops-* that have not been alarmed yet
    """

    def __init__(self):
        self.logger = logging.getLogger(info["submodule"])

    def run(self):
        """Run the alarm module"""
        ret = get_initial_alarm_result()
        ret["info"] = info
        # Only fields that are actually mapped: the connectors render every entry of this list,
        # and the old list asked for agent.hostname (never set by filebeat 8+), ioc.domain (not a
        # RedELK field - it is ioc.value) and alarm.alarm_filehash (another module's data).
        ret["fields"] = [
            "@timestamp",
            "agent.name",
            "host.name",
            "user.name",
            "ioc.type",
            "ioc.value",
            "file.name",
            "file.hash.md5",
            "c2.message",
        ]
        ret["groupby"] = []
        for result in self.alarm_dummy():
            ret["hits"]["hits"].append(result)
            ret["mutations"][result["_id"]] = {"test": "extra_data"}
            ret["hits"]["total"] += 1

        self.logger.info("finished running module. result: %s hits", ret["hits"]["total"])
        return ret

    def alarm_dummy(self):
        """This check returns the last IOC in rtops-* that have not been alarmed yet"""
        es_query = "c2.log.type:ioc AND NOT tags:alarm_*"
        es_results = get_query(es_query, 1, index="rtops-*")
        self.logger.debug("dummy alarm candidates: %s", es_results)

        return es_results
