#!/usr/bin/env python3
"""
RedELK client installer.

This script is part of a package generated by `redelkctl package`. It is self-contained: it only
uses the Python standard library, and every value it needs comes from the manifest.json next to
it. Run it as root on the redirector or C2 server:

    sudo ./install.py

It is idempotent - running it again after regenerating the package (for example because you
rotated the certificates) updates the configuration in place.

Options:
    --dry-run       show what would happen without changing anything
    --no-filebeat   skip installing/starting filebeat (configuration is still written)
    --uninstall     remove what this installer added
"""

from __future__ import annotations

import argparse
import json
import os
import pwd
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MANIFEST = HERE / "manifest.json"

FILEBEAT_CONFIG_DIR = Path("/etc/filebeat")
FILEBEAT_CERT_DIR = FILEBEAT_CONFIG_DIR / "certs"
FILEBEAT_INPUTS_DIR = FILEBEAT_CONFIG_DIR / "inputs.d"
REDELK_BIN_DIR = Path("/usr/share/redelk/bin")
REDELK_LOG_DIR = Path("/var/log/redelk")
KEYRING = Path("/etc/apt/keyrings/elastic.asc")
ELASTIC_KEY_URL = "https://artifacts.elastic.co/GPG-KEY-elasticsearch"

GREEN, YELLOW, RED, RESET = "\033[32m", "\033[33m", "\033[31m", "\033[0m"


class InstallError(Exception):
    """Something went wrong that the operator has to fix."""


def info(message: str) -> None:
    print(f"{GREEN}[*]{RESET} {message}")


def warn(message: str) -> None:
    print(f"{YELLOW}[!]{RESET} {message}")


def fail(message: str) -> None:
    print(f"{RED}[X]{RESET} {message}", file=sys.stderr)


class Runner:
    """Runs commands, honouring --dry-run and failing loudly."""

    def __init__(self, dry_run: bool):
        self.dry_run = dry_run

    def run(self, argv: list[str], *, check: bool = True, quiet: bool = False) -> int:
        if self.dry_run:
            print(f"    would run: {' '.join(argv)}")
            return 0
        result = subprocess.run(
            argv,
            check=False,
            stdout=subprocess.PIPE if quiet else None,
            stderr=subprocess.STDOUT if quiet else None,
            text=True,
        )
        if check and result.returncode != 0:
            output = f"\n{result.stdout}" if quiet and result.stdout else ""
            raise InstallError(f"command failed ({result.returncode}): {' '.join(argv)}{output}")
        return result.returncode

    def write(self, path: Path, content: bytes, mode: int = 0o644) -> None:
        if self.dry_run:
            print(f"    would write: {path} ({len(content)} bytes, mode {mode:o})")
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(path.suffix + ".redelk-tmp")
        with open(os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode), "wb") as handle:
            handle.write(content)
        os.replace(tmp, path)
        os.chmod(path, mode)

    def copy(self, src: Path, dst: Path, mode: int = 0o644) -> None:
        self.write(dst, src.read_bytes(), mode)

    def mkdir(self, path: Path, mode: int = 0o755) -> None:
        if self.dry_run:
            print(f"    would create directory: {path}")
            return
        path.mkdir(parents=True, exist_ok=True)
        os.chmod(path, mode)

    def remove(self, path: Path) -> None:
        if self.dry_run:
            print(f"    would remove: {path}")
            return
        if path.is_dir() and not path.is_symlink():
            shutil.rmtree(path, ignore_errors=True)
        elif path.exists() or path.is_symlink():
            path.unlink(missing_ok=True)


def load_manifest() -> dict:
    if not MANIFEST.is_file():
        raise InstallError(f"{MANIFEST} not found - run this script from inside its package")
    with MANIFEST.open(encoding="utf-8") as handle:
        return json.load(handle)


def require_root() -> None:
    if os.geteuid() != 0:
        raise InstallError("this installer must run as root (try: sudo ./install.py)")


def detect_apt() -> None:
    if not Path("/etc/debian_version").is_file() or shutil.which("apt-get") is None:
        raise InstallError(
            "this installer supports Debian/Ubuntu (apt) systems. On other distributions, "
            "install filebeat yourself and copy filebeat.yml, inputs.d/ and certs/ into "
            "/etc/filebeat manually."
        )


def installed_filebeat_version() -> str | None:
    if shutil.which("dpkg-query") is None:
        return None
    result = subprocess.run(
        ["dpkg-query", "-W", "-f=${Version}", "filebeat"],
        check=False,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip() or None if result.returncode == 0 else None


def add_elastic_repository(runner: Runner, version: str) -> None:
    """Add the Elastic APT repository using a keyring file.

    `apt-key` was deprecated in Debian 11 and removed in Debian 12 / Ubuntu 24.04, which is why
    the old shell installer silently failed on modern systems.
    """
    major = version.split(".")[0]
    sources = Path(f"/etc/apt/sources.list.d/elastic-{major}.x.list")

    if not KEYRING.is_file():
        info(f"Fetching the Elastic signing key into {KEYRING}")
        runner.mkdir(KEYRING.parent)
        if runner.dry_run:
            print(f"    would download {ELASTIC_KEY_URL}")
        else:
            import urllib.request

            with urllib.request.urlopen(ELASTIC_KEY_URL, timeout=30) as response:
                key = response.read()
            if b"BEGIN PGP PUBLIC KEY BLOCK" not in key:
                raise InstallError(f"{ELASTIC_KEY_URL} did not return a PGP public key")
            runner.write(KEYRING, key, 0o644)

    line = (
        f"deb [signed-by={KEYRING}] https://artifacts.elastic.co/packages/{major}.x/apt "
        "stable main\n"
    )
    runner.write(sources, line.encode("utf-8"))

    # Old installs used apt-key plus an unsigned entry; leaving it in place breaks `apt update`.
    legacy = Path("/etc/apt/sources.list.d/elastic-7.x.list")
    if legacy.is_file() and legacy != sources:
        warn(f"removing the stale {legacy} from an older RedELK install")
        runner.remove(legacy)


def install_filebeat(runner: Runner, version: str) -> None:
    current = installed_filebeat_version()
    if current == version:
        info(f"Filebeat {version} is already installed")
    else:
        if current:
            info(f"Upgrading filebeat {current} -> {version}")
        else:
            info(f"Installing filebeat {version}")
        add_elastic_repository(runner, version)
        runner.run(["apt-get", "update"], quiet=True)
        env_argv = ["apt-get", "install", "-y", "--allow-downgrades", f"filebeat={version}"]
        runner.run(env_argv, quiet=True)

    # Pin the package so an unrelated `apt upgrade` cannot move filebeat out of step with the
    # RedELK server's Logstash version.
    runner.write(
        Path("/etc/apt/preferences.d/redelk-filebeat"),
        (
            "# Pinned by RedELK: filebeat must match the Elastic version of the RedELK server.\n"
            "Package: filebeat\n"
            f"Pin: version {version}\n"
            "Pin-Priority: 1001\n"
        ).encode("utf-8"),
    )


def install_configuration(runner: Runner, manifest: dict) -> None:
    info("Installing the filebeat configuration")
    runner.mkdir(FILEBEAT_CONFIG_DIR)
    runner.mkdir(FILEBEAT_INPUTS_DIR)
    runner.mkdir(FILEBEAT_CERT_DIR, 0o750)
    runner.mkdir(Path("/var/log/filebeat"), 0o750)

    original = FILEBEAT_CONFIG_DIR / "filebeat.yml"
    backup = FILEBEAT_CONFIG_DIR / "filebeat.yml.pre-redelk"
    if original.is_file() and not backup.is_file():
        marker = b"RedELK"
        if marker not in original.read_bytes():
            info(f"Backing up the existing filebeat.yml to {backup}")
            runner.copy(original, backup)

    runner.copy(HERE / "filebeat.yml", original, 0o600)

    # Remove inputs from a previous RedELK install that this host no longer runs; the old shell
    # installer copied every C2's inputs onto every host and never cleaned up.
    wanted = {path.name for path in (HERE / "inputs.d").glob("*.yml")}
    if FILEBEAT_INPUTS_DIR.is_dir():
        for existing in FILEBEAT_INPUTS_DIR.glob("*.yml"):
            if existing.name not in wanted:
                warn(f"removing stale input {existing.name}")
                runner.remove(existing)
    for source in sorted((HERE / "inputs.d").glob("*.yml")):
        runner.copy(source, FILEBEAT_INPUTS_DIR / source.name, 0o640)

    for source in sorted((HERE / "certs").glob("*")):
        mode = 0o600 if source.suffix == ".key" else 0o644
        runner.copy(source, FILEBEAT_CERT_DIR / source.name, mode)


def ensure_user(runner: Runner, username: str, shell: str) -> None:
    try:
        pwd.getpwnam(username)
        info(f"User {username} already exists")
        runner.run(["usermod", "-s", shell, username])
        return
    except KeyError:
        pass
    info(f"Creating the {username} user")
    # No password is set at all: the account is reachable through the RedELK ssh key only.
    runner.run(["useradd", "--create-home", "--shell", shell, username])
    runner.run(["passwd", "--lock", username], check=False)


def install_sync(runner: Runner, manifest: dict) -> None:
    """Everything needed for the RedELK server to pull artefacts off this C2 server."""
    username = manifest.get("ssh_user", "scponly")

    info("Installing rush (restricted shell)")
    if shutil.which("rush") is None:
        runner.run(["apt-get", "install", "-y", "rush"], quiet=True)
    rush_path = shutil.which("rush") or "/usr/sbin/rush"

    rush_rc = Path("/etc/rush.rc")
    if rush_rc.is_file() and b"RedELK" not in rush_rc.read_bytes():
        backup = Path("/etc/rush.rc.pre-redelk")
        if not backup.is_file():
            runner.copy(rush_rc, backup)
    runner.copy(HERE / "rush.rc", rush_rc, 0o644)

    ensure_user(runner, username, rush_path)

    home = Path(pwd.getpwnam(username).pw_dir) if not runner.dry_run else Path(f"/home/{username}")
    ssh_dir = home / ".ssh"
    authorized = ssh_dir / "authorized_keys"
    public_key = (HERE / "redelk_authorized_key.pub").read_bytes()

    info(f"Authorising the RedELK server's ssh key for {username}")
    runner.mkdir(ssh_dir, 0o700)
    existing = authorized.read_bytes() if authorized.is_file() else b""
    key_body = public_key.split(b" ")[1] if b" " in public_key else public_key
    if key_body in existing:
        info("The RedELK key is already authorised")
    else:
        # Keep any other keys the operator added.
        merged = (
            existing + (b"" if existing.endswith(b"\n") or not existing else b"\n") + public_key
        )
        runner.write(authorized, merged, 0o600)

    if not runner.dry_run:
        uid = pwd.getpwnam(username).pw_uid
        gid = pwd.getpwnam(username).pw_gid
        for path in (ssh_dir, authorized):
            os.chown(path, uid, gid)

    info("Installing the log synchronisation cron job")
    runner.copy(HERE / "redelk.cron", Path(f"/etc/cron.d/redelk_{manifest['type']}"), 0o644)

    scripts = HERE / "scripts"
    if scripts.is_dir() and any(scripts.iterdir()):
        info(f"Installing helper scripts into {REDELK_BIN_DIR}")
        runner.mkdir(REDELK_BIN_DIR)
        for script in sorted(scripts.iterdir()):
            runner.copy(script, REDELK_BIN_DIR / script.name, 0o755)

    runner.mkdir(REDELK_LOG_DIR, 0o755)

    if manifest["type"] == "cobaltstrike":
        _ensure_python_package(runner, "javaobj-py3", "javaobj")


def _ensure_python_package(runner: Runner, package: str, import_name: str) -> None:
    """Install a python dependency needed by a helper script.

    Debian 12+ marks the system python as externally managed, so a plain `pip install` fails.
    Prefer the distribution package, fall back to pip with --break-system-packages.
    """
    probe = subprocess.run(
        [sys.executable, "-c", f"import {import_name}"], check=False, capture_output=True
    )
    if probe.returncode == 0:
        info(f"Python package {package} is already available")
        return
    info(f"Installing the {package} python package")
    if (
        runner.run(["apt-get", "install", "-y", f"python3-{import_name}"], check=False, quiet=True)
        == 0
    ):
        return
    if runner.run([sys.executable, "-m", "pip", "install", package], check=False, quiet=True) == 0:
        return
    runner.run(
        [sys.executable, "-m", "pip", "install", "--break-system-packages", package], quiet=True
    )


def start_filebeat(runner: Runner) -> None:
    info("Enabling and starting filebeat")
    runner.run(["systemctl", "enable", "filebeat"], check=False)
    runner.run(["systemctl", "restart", "filebeat"])


def verify(runner: Runner, manifest: dict) -> None:
    if runner.dry_run:
        return
    info("Verifying the filebeat configuration")
    result = subprocess.run(
        ["filebeat", "test", "config", "-c", str(FILEBEAT_CONFIG_DIR / "filebeat.yml")],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise InstallError(f"filebeat rejected its configuration:\n{result.stdout}{result.stderr}")

    info("Testing the connection to the RedELK server")
    result = subprocess.run(
        ["filebeat", "test", "output", "-c", str(FILEBEAT_CONFIG_DIR / "filebeat.yml")],
        check=False,
        capture_output=True,
        text=True,
    )
    print((result.stdout or "") + (result.stderr or ""))
    if result.returncode != 0:
        warn(
            f"filebeat could not reach {manifest['logstash']}. Check that the RedELK server is "
            "running, that the port is reachable, and that this host's clock is correct."
        )


def uninstall(runner: Runner, manifest: dict) -> None:
    warn("Removing the RedELK client installation (collected data is left untouched)")
    runner.run(["systemctl", "stop", "filebeat"], check=False)
    runner.run(["systemctl", "disable", "filebeat"], check=False)
    for path in (
        FILEBEAT_INPUTS_DIR,
        FILEBEAT_CERT_DIR,
        Path("/etc/apt/preferences.d/redelk-filebeat"),
        Path(f"/etc/cron.d/redelk_{manifest['type']}"),
        REDELK_BIN_DIR,
    ):
        runner.remove(path)
    backup = FILEBEAT_CONFIG_DIR / "filebeat.yml.pre-redelk"
    if backup.is_file():
        runner.copy(backup, FILEBEAT_CONFIG_DIR / "filebeat.yml")
        runner.remove(backup)
    rush_backup = Path("/etc/rush.rc.pre-redelk")
    if rush_backup.is_file():
        runner.copy(rush_backup, Path("/etc/rush.rc"))
        runner.remove(rush_backup)
    warn(
        "The scponly user and its authorized_keys were left in place. Remove them with "
        "'userdel -r scponly' if you no longer need them."
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="RedELK client installer")
    parser.add_argument("--dry-run", action="store_true", help="show what would change")
    parser.add_argument(
        "--no-filebeat", action="store_true", help="do not install or start filebeat"
    )
    parser.add_argument("--uninstall", action="store_true", help="undo the installation")
    args = parser.parse_args()

    try:
        manifest = load_manifest()
        require_root()
        runner = Runner(args.dry_run)

        print()
        info(
            f"RedELK client for {manifest['name']} "
            f"({manifest['role']}, {manifest['type']}, scenario '{manifest['attack_scenario']}')"
        )
        print()

        if args.uninstall:
            uninstall(runner, manifest)
            return 0

        detect_apt()
        if not args.no_filebeat:
            install_filebeat(runner, manifest["elastic_version"])
        install_configuration(runner, manifest)
        if manifest.get("sync"):
            install_sync(runner, manifest)
        if not args.no_filebeat:
            start_filebeat(runner)
            verify(runner, manifest)

        print()
        info("Done.")
        if manifest.get("sync"):
            info(
                "The RedELK server pulls this host's artefacts over ssh; no further action is "
                "needed there."
            )
        return 0
    except InstallError as error:
        fail(str(error))
        return 1
    except KeyboardInterrupt:
        fail("interrupted")
        return 130


if __name__ == "__main__":
    sys.exit(main())
