---
# RedELK server installation tasks

- name: Calculate install mode prechecks
  ansible.builtin.import_tasks: memory.yml
  tags:
    - memory
    - redelk-setup

- name: Install required packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - packages

- name: Apply Docker preflight checks
  ansible.builtin.import_tasks: docker.yml
  tags:
    - docker

- name: Setup RedELK server
  ansible.builtin.import_tasks: redelk-setup.yml
  tags:
    - redelk-setup
