---
- name: Converge ELK servers
  hosts: elkservers
  gather_facts: true
  roles:
    - redelk-server

- name: Converge C2 servers
  hosts: c2servers
  gather_facts: true
  roles:
    - redelk-client

- name: Converge redirectors
  hosts: redirs
  gather_facts: true
  roles:
    - redelk-client
