---
- name: Restart RedELK docker containers
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ redelk_remote_base_path }}/elkserver"
    project_name: "{{ redelk_compose_project_name }}"
    files:
      - docker-compose.yml
    build: always
    state: present
