---
galaxy_info:
  author: RedELK
  description: Run './redelkctl generate' on the control node and check it against the inventory.
  license: BSD-3-Clause
  min_ansible_version: "2.15"
  galaxy_tags:
    - redelk

dependencies: []
