"""
Part of RedELK

Pure-python APR1 (Apache MD5) password hashing for the nginx basic-auth file.

nginx supports APR1 natively on every platform, unlike the crypt(3) based schemes, and Python's
`crypt` module was removed in 3.13 - so the algorithm is implemented here. It is only used for
the reverse proxy's basic auth in front of Kibana, which sits on top of Elasticsearch's own
authentication.

Authors:
- RedELK contributors
"""

from __future__ import annotations

import hashlib
import secrets

ITOA64 = "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"


def _to64(value: int, length: int) -> str:
    out = []
    for _ in range(length):
        out.append(ITOA64[value & 0x3F])
        value >>= 6
    return "".join(out)


def apr1(password: str, salt: str | None = None) -> str:
    """Return an APR1 (``$apr1$``) hash of `password`."""
    if salt is None:
        salt = "".join(secrets.choice(ITOA64) for _ in range(8))
    salt = salt[:8]

    pwd = password.encode("utf-8")
    salt_bytes = salt.encode("ascii")

    context = hashlib.md5(pwd + b"$apr1$" + salt_bytes)

    final = hashlib.md5(pwd + salt_bytes + pwd).digest()
    length = len(pwd)
    while length > 0:
        context.update(final[: min(length, 16)])
        length -= 16
    # Then something really weird, straight from the original Apache implementation: for every
    # bit set in the password length, add either a NUL byte or the password's first byte.
    length = len(pwd)
    while length:
        context.update(b"\0" if length & 1 else pwd[:1])
        length >>= 1

    digest = context.digest()

    # 1000 strengthening rounds.
    for i in range(1000):
        ctx = hashlib.md5()
        ctx.update(pwd if i & 1 else digest)
        if i % 3:
            ctx.update(salt_bytes)
        if i % 7:
            ctx.update(pwd)
        ctx.update(digest if i & 1 else pwd)
        digest = ctx.digest()

    encoded = (
        _to64((digest[0] << 16) | (digest[6] << 8) | digest[12], 4)
        + _to64((digest[1] << 16) | (digest[7] << 8) | digest[13], 4)
        + _to64((digest[2] << 16) | (digest[8] << 8) | digest[14], 4)
        + _to64((digest[3] << 16) | (digest[9] << 8) | digest[15], 4)
        + _to64((digest[4] << 16) | (digest[10] << 8) | digest[5], 4)
        + _to64(digest[11], 2)
    )
    return f"$apr1${salt}${encoded}"


def htpasswd_file(entries: dict[str, str]) -> str:
    """Render a complete htpasswd file for the given {username: password} mapping.

    The file is rendered from scratch every time on purpose: RedELK used to ship a checked-in
    htpasswd containing a second, undocumented 'elastic' account whose password hash was public
    in the git repository, and which no installer ever removed.
    """
    lines = ["# Generated by redelkctl - do not edit, change the passwords in redelk.secrets.yml"]
    for user, password in entries.items():
        lines.append(f"{user}:{apr1(password)}")
    return "\n".join(lines) + "\n"


def verify(password: str, hashed: str) -> bool:
    """Verify a password against an APR1 hash (used by the test suite)."""
    parts = hashed.split("$")
    if len(parts) != 4 or parts[1] != "apr1":
        return False
    return secrets.compare_digest(apr1(password, parts[2]), hashed)
