"""
Part of RedELK

Rendering of every generated file: the docker environment, the daemon configuration, the nginx
basic-auth file, Elasticsearch heap settings, cron schedules, and the per-host Filebeat
configuration that used to be produced by four different shell scripts with sed.

Two rules apply everywhere in this module:

  * Generated files carry a header saying so, and are safe to delete - `redelkctl generate`
    recreates them.
  * Files that RedELK mutates at runtime (the ip/domain lists, which are synchronised with
    Elasticsearch) are only written when they do not exist yet, so a regeneration never throws
    away operational data.

Authors:
- RedELK contributors
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from . import certs, htpasswd
from . import config as config_module
from .schema import C2_TYPES, ConfigError

try:
    from jinja2 import Environment, FileSystemLoader, StrictUndefined
except ImportError as exc:  # pragma: no cover - handled by the bootstrap in ./redelkctl
    raise ConfigError(
        "Jinja2 is not installed. Run ./redelkctl (which bootstraps its own virtualenv) or "
        "'pip install -r tools/requirements.txt'."
    ) from exc

GENERATED_HEADER = (
    "# This file is generated by redelkctl from redelk.yml - do not edit it by hand.\n"
    "# Change redelk.yml and run './redelkctl generate' instead.\n"
)

TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"


@dataclass
class RenderResult:
    """What a render pass produced, for reporting to the user."""

    written: list[Path]
    skipped: list[Path]
    warnings: list[str] = field(default_factory=list)

    def add(self, path: Path, changed: bool) -> None:
        (self.written if changed else self.skipped).append(path)


def environment() -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATE_DIR)),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["to_yaml_scalar"] = _to_yaml_scalar
    return env


def _to_yaml_scalar(value: Any) -> str:
    """Quote a value so it is safe as a YAML scalar."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    return json.dumps(text)


def write_if_changed(path: Path, content: str | bytes, *, mode: int = 0o644) -> bool:
    """Write `content` to `path` when it differs. Returns True when the file was written."""
    data = content.encode("utf-8") if isinstance(content, str) else content
    if path.is_file() and path.read_bytes() == data:
        # Still make sure the permissions are what we expect.
        if (path.stat().st_mode & 0o777) != mode:
            os.chmod(path, mode)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with open(os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode), "wb") as handle:
        handle.write(data)
    os.replace(tmp, path)
    os.chmod(path, mode)
    return True


def write_if_absent(path: Path, content: str, *, mode: int = 0o644) -> bool:
    """Write `content` only when `path` does not exist yet."""
    if path.exists():
        return False
    return write_if_changed(path, content, mode=mode)


# --------------------------------------------------------------------------------------------
# Server side
# --------------------------------------------------------------------------------------------


def render_env(cfg: config_module.Config, elkserver: Path, result: RenderResult) -> None:
    """The docker compose .env file."""
    env = environment()
    memory = config_module.compute_memory(cfg)
    server = cfg.raw["server"]
    tls = server["tls"]

    if tls["mode"] == "letsencrypt":
        cert_dir = "./mounts/certbot/conf/live/" + cfg.primary_hostname
    elif tls["mode"] == "custom":
        cert_dir = "./mounts/nginx-certs"
    else:
        cert_dir = "./mounts/nginx-certs/self-signed"

    # Compose profiles gate the optional services. Empty means "core stack only".
    profiles = (["full"] if cfg.is_full else []) + (["letsencrypt"] if cfg.letsencrypt else [])

    content = env.get_template("env.j2").render(
        header=GENERATED_HEADER,
        config=cfg,
        server=server,
        secrets=cfg.secrets,
        elastic=cfg.raw["elastic"],
        memory=memory,
        image_tag=cfg.image_tag,
        nginx_cert_dir=cert_dir,
        compose_profiles=",".join(profiles),
    )
    result.add(elkserver / ".env", write_if_changed(elkserver / ".env", content, mode=0o600))


def render_daemon_config(cfg: config_module.Config, elkserver: Path, result: RenderResult) -> None:
    """/etc/redelk/config.json for the RedELK daemon."""
    target = elkserver / "mounts" / "redelk-config" / "etc" / "redelk" / "config.json"
    document = config_module.as_daemon_config(cfg)
    content = json.dumps(document, indent=4, sort_keys=False) + "\n"
    result.add(target, write_if_changed(target, content, mode=0o600))


def render_htpasswd(cfg: config_module.Config, elkserver: Path, result: RenderResult) -> None:
    """nginx basic auth in front of Kibana.

    Rendered from scratch: the file that used to ship in the repository contained a second
    'elastic' account whose apr1 hash was public.
    """
    target = elkserver / "mounts" / "nginx-config" / "htpasswd.users.template"
    password = cfg.secrets["redelk_password"]

    # Each apr1 hash uses a fresh random salt, so the rendered bytes differ on every run. Only
    # rewrite when the existing file does not actually authenticate the current password -
    # otherwise every 'redelkctl generate' would show a spurious change.
    if target.is_file():
        entries = dict(
            line.split(":", 1)
            for line in target.read_text(encoding="utf-8").splitlines()
            if ":" in line and not line.startswith("#")
        )
        if set(entries) == {"redelk"} and htpasswd.verify(password, entries["redelk"]):
            result.add(target, False)
            return

    content = htpasswd.htpasswd_file({"redelk": password})
    result.add(target, write_if_changed(target, content, mode=0o644))


def render_server_cron(cfg: config_module.Config, elkserver: Path, result: RenderResult) -> None:
    """The cron file inside the redelk-base container.

    The rsync entries used to be a commented-out example that every operator had to hand-edit;
    they are now derived from the c2_servers list.
    """
    env = environment()
    jobs = [
        {
            "name": c2.name,
            "host": c2.host,
            "user": c2.ssh.get("user", "scponly"),
            "port": int(c2.ssh.get("port", 22)),
        }
        for c2 in cfg.c2_by_ingest("files")
    ]
    content = env.get_template("cron/redelk-server.j2").render(
        header=GENERATED_HEADER, jobs=jobs, config=cfg
    )
    target = elkserver / "mounts" / "redelk-config" / "etc" / "cron.d" / "redelk"
    # cron refuses to run files that are group/world writable.
    result.add(target, write_if_changed(target, content, mode=0o644))


def render_lists(cfg: config_module.Config, elkserver: Path, result: RenderResult) -> None:
    """Seed the ip/domain/useragent lists.

    These are only written when absent: RedELK keeps them in sync with Elasticsearch at runtime
    (enrich_synciplists / enrich_syncdomainslists), so overwriting them would discard entries
    operators added through Kibana.
    """
    lists = cfg.raw["lists"]
    base = elkserver / "mounts" / "redelk-config" / "etc" / "redelk"
    files = {
        "iplist_redteam.conf": (
            "Red team IP addresses, seeded from redelk.yml",
            lists["redteam_ips"],
        ),
        "iplist_customer.conf": ("Customer IP addresses", lists["customer_ips"]),
        "iplist_blueteam.conf": ("Known blue team IP addresses", lists["blueteam_ips"]),
        "iplist_unknown.conf": ("Unclassified IP addresses seen in traffic", []),
        "iplist_alarmed.conf": ("IP addresses that already triggered an alarm", []),
        "domainslist_redteam.conf": ("Red team domains", lists["redteam_domains"]),
        "roguedomains.conf": ("Domains implants must never talk to", lists["rogue_domains"]),
        "rogue_useragents.conf": ("User agents that indicate scanning", lists["rogue_useragents"]),
    }
    for filename, (description, values) in files.items():
        content = (
            f"# {description}\n"
            "# Seeded from redelk.yml on first run. RedELK keeps this file in sync with\n"
            "# Elasticsearch, so edit it in Kibana rather than here.\n"
            "# One entry per line, '#' starts a comment.\n"
        )
        content += "".join(f"{value}\n" for value in values)
        target = base / filename
        result.add(target, write_if_absent(target, content))


def render_nginx(cfg: config_module.Config, elkserver: Path, result: RenderResult) -> None:
    """nginx site configuration.

    The old installer commented include lines in and out with sed depending on the install
    profile; the template now simply branches on the profile.
    """
    env = environment()
    content = env.get_template("nginx/default.conf.j2").render(
        header=GENERATED_HEADER.replace("#", "#", 1),
        config=cfg,
        server=cfg.raw["server"],
        full=cfg.is_full,
    )
    target = elkserver / "mounts" / "nginx-config" / "default.conf.template"
    result.add(target, write_if_changed(target, content))


def render_ilm_policy(cfg: config_module.Config, elkserver: Path, result: RenderResult) -> None:
    """The index lifecycle policy, derived from elastic.retention.

    Deliberately rollover-free. RedELK writes to date-stamped indices (rtops-YYYY.MM.dd) and
    *updates* documents in place - enrichment modules add fields, alarms add tags - which a
    rollover alias would make needlessly awkward. Without a rollover action, ILM ages an index
    from its creation date, which is exactly the retention model RedELK wants.
    """
    retention = cfg.raw["elastic"]["retention"]
    phases: dict[str, Any] = {
        "hot": {"min_age": "0ms", "actions": {"set_priority": {"priority": 100}}},
        "warm": {
            "min_age": f"{retention['hot_days']}d",
            "actions": {"set_priority": {"priority": 50}, "forcemerge": {"max_num_segments": 1}},
        },
    }
    if retention["delete_days"]:
        phases["delete"] = {
            "min_age": f"{retention['delete_days']}d",
            "actions": {"delete": {}},
        }

    document = {"policy": {"_meta": {"managed_by": "redelk"}, "phases": phases}}
    target = (
        elkserver
        / "docker"
        / "redelk-base"
        / "redelkinstalldata"
        / "templates"
        / "redelk_elasticsearch_ilm.json"
    )
    result.add(target, write_if_changed(target, json.dumps(document, indent=2) + "\n"))


def render_bloodhound(cfg: config_module.Config, elkserver: Path, result: RenderResult) -> None:
    """BloodHound CE reads its database credentials from a JSON file, not from the environment.

    https://github.com/SpecterOps/BloodHound/issues/9 - which is why the installer used to sed
    three passwords into a committed file and left {{PLACEHOLDERS}} behind on the limited profile.
    """
    if not cfg.is_full:
        return
    env = environment()
    letsencrypt_email = cfg.raw["server"]["tls"]["letsencrypt"]["email"]
    content = env.get_template("bloodhound.config.json.j2").render(
        hostname=cfg.primary_hostname,
        bloodhound_port=cfg.raw["server"]["ports"]["bloodhound"],
        postgres_user="bloodhound",
        postgres_database="bloodhound",
        postgres_password=cfg.secrets["postgres_password"],
        neo4j_password=cfg.secrets["neo4j_password"],
        bloodhound_password=cfg.secrets["bloodhound_password"],
        admin_email=letsencrypt_email or f"admin@{cfg.primary_hostname}",
    )
    target = elkserver / "mounts" / "bloodhound-config" / "bloodhound.config.json"
    result.add(target, write_if_changed(target, content, mode=0o600))


def render_compose_override(
    cfg: config_module.Config, elkserver: Path, result: RenderResult
) -> None:
    """Publish the BloodHound port only on the full profile.

    A compose profile can include or exclude a whole service, but not a single port mapping, and
    binding 8443 on a limited install would fail on any host already using that port for
    something else.
    """
    target = elkserver / "docker-compose.override.yml"
    if not cfg.is_full:
        if target.is_file():
            target.unlink()
            result.add(target, True)
        return

    content = (
        GENERATED_HEADER
        + "services:\n"
        + "  nginx:\n"
        + "    ports:\n"
        + '      - "${BIND_BLOODHOUND:-127.0.0.1}:${PORT_BLOODHOUND:-8443}:8443"\n'
    )
    result.add(target, write_if_changed(target, content))


def render_server(cfg: config_module.Config) -> RenderResult:
    """Render everything the RedELK server needs."""
    result = RenderResult(written=[], skipped=[])
    elkserver = cfg.root / "elkserver"
    mounts = elkserver / "mounts"

    certs.ensure_all(cfg, mounts)
    certs.ensure_ssh_key(mounts)

    render_env(cfg, elkserver, result)
    render_daemon_config(cfg, elkserver, result)
    render_htpasswd(cfg, elkserver, result)
    render_server_cron(cfg, elkserver, result)
    render_lists(cfg, elkserver, result)
    render_nginx(cfg, elkserver, result)
    render_ilm_policy(cfg, elkserver, result)
    render_bloodhound(cfg, elkserver, result)
    render_compose_override(cfg, elkserver, result)

    if cfg.raw["server"]["tls"]["mode"] == "self-signed":
        _render_selfsigned_nginx_cert(cfg, mounts, result)

    # Must come last: it covers everything written above.
    result.warnings.extend(certs.apply_container_ownership(mounts))

    return result


def _render_selfsigned_nginx_cert(
    cfg: config_module.Config, mounts: Path, result: RenderResult
) -> None:
    """nginx needs a certificate even when Let's Encrypt is not used."""
    target_dir = mounts / "nginx-certs" / "self-signed"
    cert_path = target_dir / "fullchain.pem"
    key_path = target_dir / "privkey.pem"
    paths = certs.CertificatePaths(mounts)
    ca_cert, ca_key = certs.ensure_ca(paths, int(cfg.raw["server"]["tls"]["ca_validity_days"]))
    dns_names, ips = cfg.cert_names()
    created = certs._ensure_leaf(  # noqa: SLF001 - internal helper, same package
        ca_cert,
        ca_key,
        cert_path,
        key_path,
        cfg.primary_hostname,
        dns_names,
        ips,
        int(cfg.raw["server"]["tls"]["cert_validity_days"]),
        server=True,
    )
    if created:
        # nginx serves the leaf plus the CA so browsers can build the chain once the CA is
        # trusted, which is what operators do with the RedELK CA anyway.
        chain = cert_path.read_bytes() + certs._cert_pem(ca_cert)  # noqa: SLF001
        cert_path.write_bytes(chain)
    result.add(cert_path, created)


# --------------------------------------------------------------------------------------------
# Client side (C2 servers and redirectors)
# --------------------------------------------------------------------------------------------


def _filebeat_inputs_for(cfg: config_module.Config, host) -> list[dict[str, Any]]:
    """Which filebeat input templates a host needs.

    The old installer copied every C2's inputs onto every teamserver, which meant a Sliver
    server also harvested (non-existent) Cobalt Strike paths and a PoshC2 server ran the Cobalt
    Strike export cron.
    """
    if isinstance(host, config_module.Redirector):
        return [{"template": "filebeat/inputs/redirector.yml.j2", "name": host.type}]
    return [{"template": f"filebeat/inputs/{host.type}.yml.j2", "name": host.type}]


def render_client_package(cfg: config_module.Config, host, destination: Path) -> Path:
    """Render a complete, self-contained installation package for one host."""
    env = environment()
    is_redirector = isinstance(host, config_module.Redirector)
    scenario = cfg.attack_scenario_for(host)
    package = destination / host.name
    package.mkdir(parents=True, exist_ok=True)

    mutual_auth = bool(cfg.raw["server"]["tls"]["mutual_auth"])

    # 1. Filebeat main config.
    main_config = env.get_template("filebeat/filebeat.yml.j2").render(
        header=GENERATED_HEADER,
        name=host.name,
        endpoint=cfg.ingest_endpoint,
        mutual_auth=mutual_auth,
        attack_scenario=scenario,
        is_redirector=is_redirector,
    )
    write_if_changed(package / "filebeat.yml", main_config)

    # 2. Inputs.
    inputs_dir = package / "inputs.d"
    inputs_dir.mkdir(parents=True, exist_ok=True)
    for spec in _filebeat_inputs_for(cfg, host):
        rendered = env.get_template(spec["template"]).render(
            header=GENERATED_HEADER,
            attack_scenario=scenario,
            base_path=getattr(host, "base_path", ""),
            host=host,
        )
        write_if_changed(inputs_dir / f"{spec['name']}.yml", rendered)

    # 3. TLS material.
    certs_dir = package / "certs"
    certs_dir.mkdir(parents=True, exist_ok=True)
    write_if_changed(
        certs_dir / "redelkCA.crt", certs.ca_certificate_pem(cfg.root / "elkserver" / "mounts")
    )
    if mutual_auth:
        source = cfg.root / "elkserver" / "mounts" / "logstash-config" / "certs_clients" / host.name
        for suffix in ("crt", "key"):
            src = source / f"{host.name}.{suffix}"
            if not src.is_file():
                raise ConfigError(
                    f"missing client certificate {src} - run './redelkctl generate' first"
                )
            write_if_changed(
                certs_dir / f"client.{suffix}",
                src.read_bytes(),
                mode=0o600 if suffix == "key" else 0o644,
            )

    # 4. C2 log synchronisation (cron + helper scripts + ssh key).
    manifest: dict[str, Any] = {
        "name": host.name,
        "role": "redirector" if is_redirector else "c2server",
        "type": host.type,
        "attack_scenario": scenario,
        "elastic_version": cfg.elastic_version,
        "mutual_auth": mutual_auth,
        "logstash": cfg.ingest_endpoint,
        "sync": False,
    }

    if not is_redirector and host.ingest == "files":
        manifest["sync"] = True
        manifest["base_path"] = host.base_path
        manifest["ssh_user"] = host.ssh.get("user", "scponly")

        cron = env.get_template("cron/client.j2").render(
            header=GENERATED_HEADER, host=host, base_path=host.base_path
        )
        write_if_changed(package / "redelk.cron", cron)

        rush = env.get_template("rush.rc.j2").render(header=GENERATED_HEADER)
        write_if_changed(package / "rush.rc", rush)

        ssh_pub = cfg.root / "elkserver" / "mounts" / "redelk-ssh" / "id_rsa.pub"
        if ssh_pub.is_file():
            write_if_changed(package / "redelk_authorized_key.pub", ssh_pub.read_bytes())

        scripts_dir = package / "scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)
        for script in _sync_scripts_for(host.type):
            src = cfg.root / "c2servers" / "scripts" / script
            if src.is_file():
                write_if_changed(scripts_dir / script, src.read_bytes(), mode=0o755)

    # 5. The installer itself and its manifest.
    installer = (TEMPLATE_DIR / "client" / "install.py").read_text(encoding="utf-8")
    write_if_changed(package / "install.py", installer, mode=0o755)
    write_if_changed(package / "manifest.json", json.dumps(manifest, indent=2) + "\n")
    readme = env.get_template("client/README.md.j2").render(
        host=host, manifest=manifest, config=cfg
    )
    write_if_changed(package / "README.md", readme)

    return package


def _sync_scripts_for(c2_type: str) -> list[str]:
    return {
        "cobaltstrike": [
            "export_cobaltstrikedata.sh",
            "exportcsdata.py",
            "copydownloads_cobaltstrike.sh",
        ],
        "outflankstage1": ["copydownloads_outflankstage1.sh"],
        "sliver": [],
        "poshc2": [],
    }.get(c2_type, [])


def render_clients(cfg: config_module.Config, destination: Path | None = None) -> list[Path]:
    """Render installation packages for every file-based C2 server and every redirector."""
    destination = destination or (cfg.root / "build" / "packages")
    destination.mkdir(parents=True, exist_ok=True)
    packages = []
    for host in [*cfg.c2_by_ingest("files"), *[r for r in cfg.redirectors if r.enabled]]:
        packages.append(render_client_package(cfg, host, destination))
    return packages


def api_c2_summary(cfg: config_module.Config) -> list[str]:
    """Human readable summary of the API-based C2 servers, which need no package at all."""
    return [
        f"{c2.name} ({C2_TYPES[c2.type]['label']}) - polled from the RedELK server at "
        f"{c2.api.get('url', '?')}"
        for c2 in cfg.c2_by_ingest("api")
    ]
