# Part of RedELK
#
# In this file we configure the logstash filters for email inputs
#
# Author: Outflank B.V. / Marc Smeets
#

filter {
  if [infra][log][type] == "email" {

    # Set the timestamp from the log to @timestamp
    # example: Wed, 29 Jul 2020 10:54:29 +0200
    date {
      match => [ "date", "EEE, dd MMM yyyy HH:mm:ss Z" ]
      target => "@timestamp"
    }

    # Add metadata for SIEM
    mutate {
      add_field => {
        "[event][kind]" => "event"
        "[event][category]" => "email"
        "[event][module]" => "redelk"
        "[event][dataset]" => "email"
        "[event][action]" => "email"
        "[event][type]" => "info"
      }
    }
  }
}
