---
collections:
  - name: ansible.posix
    version: "2.1.0"
  - name: community.docker
    version: "5.1.0"
  - name: community.crypto
    version: "3.12.1"
  - name: community.general
    version: "11.4.0"
