---
elkservers:
  hosts:
    redelk-live-01:
      ansible_host: 203.0.113.10
      ansible_user: root

c2servers:
  hosts:
    c2-live-01:
      ansible_host: 203.0.113.20
      ansible_user: root
      redelk_identifier: c2-live-01

redirs:
  hosts:
    redir-live-01:
      ansible_host: 203.0.113.30
      ansible_user: root
      redelk_identifier: redir-live-01
      associated_backend: c2-live-01
