---
redelk_local_repo_path: "{{ playbook_dir | dirname }}"
redelk_remote_base_path: /opt/redelk
redelk_identifier: "{{ inventory_hostname }}"
es_version: "7.17.9"
redelk_filebeat_package: "filebeat={{ es_version }}"
redelk_filebeat_ca_path: /etc/filebeat/redelkCA.crt
redelk_filebeat_main_config: /etc/filebeat/filebeat.yml
redelk_filebeat_inputs_dir: /etc/filebeat/inputs.d
redelk_filebeat_redir_input_file: "{{ redelk_filebeat_inputs_dir }}/redirs.yml"
redelk_log_dir: /var/log/redelk
redelk_bin_dir: /usr/share/redelk/bin
redelk_sync_user: scponly
redelk_sync_user_home: "/home/{{ redelk_sync_user }}"
redelk_sync_user_shell: /usr/sbin/rush
redelk_sync_public_key_path: "{{ redelk_local_repo_path }}/c2servers/ssh/id_rsa.pub"
redelk_c2_filebeat_inputs:
  - cobaltstrike
  - poshc2
  - sliver
redelk_c2_sync_jobs:
  - cobaltstrike
  - sliver
