#!/usr/bin/env python3
"""
Part of RedELK

Builds the compact MITRE ATT&CK dictionary that RedELK ships with, from the official
attack-stix-data bundle.

The full Enterprise STIX bundle is ~50MB of relationships, mitigations, groups and software that
the enrichment module has no use for. This distills it down to the few hundred kilobytes RedELK
actually needs: technique id -> name, tactics, url, and the deprecation/revocation state that lets
us remap identifiers produced by C2 frameworks that were pinned to an older ATT&CK release.

Run it from the repository root:

    ./tools/generate_attack_dictionary.py

The result is written to elkserver/docker/redelk-base/redelkinstalldata/data/attack/, and is only
rewritten when the ATT&CK content actually changed, so re-running does not produce a diff.

Authors:
- RedELK contributors
"""

from __future__ import annotations

import argparse
import json
import os
import re
import socket
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent

# Pinned to a specific Enterprise release for reproducibility. The unversioned
# enterprise-attack.json floats to whatever is latest, which is how a v19 bundle - TA0005 renamed
# "Stealth" and a new tactic TA0112 "Defense Impairment" - once landed silently. Bumping ATT&CK is
# now a deliberate edit of this URL plus a matching update to CANONICAL_TACTICS in
# tests/test_attack_dictionary_tactics_canonical.py, which guards the pinned tactic set.
DEFAULT_URL = (
    "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/"
    "enterprise-attack/enterprise-attack-19.2.json"
)
DEFAULT_OUTPUT = (
    REPO_ROOT
    / "elkserver"
    / "docker"
    / "redelk-base"
    / "redelkinstalldata"
    / "data"
    / "attack"
    / "enterprise-attack.json"
)
DEFAULT_DOMAIN = "enterprise-attack"
DOWNLOAD_TIMEOUT = 180

GENERATED_BY = (
    "Generated by tools/generate_attack_dictionary.py from the MITRE ATT&CK STIX data. "
    "Do not edit by hand."
)

TECHNIQUE_ID = re.compile(r"^T\d{4}(\.\d{3})?$")


class GeneratorError(Exception):
    """Anything that should stop the generator with a readable message."""


def download(url: str) -> bytes:
    """Fetch the STIX bundle, turning every failure mode into one clear message."""
    request = urllib.request.Request(url, headers={"User-Agent": "RedELK/attack-dictionary"})
    try:
        with urllib.request.urlopen(request, timeout=DOWNLOAD_TIMEOUT) as response:
            # urlopen already raises on >=400, but a redirect to an error page would not.
            if response.status != 200:
                raise GeneratorError(f"{url} returned HTTP {response.status}")
            payload = response.read()
    except urllib.error.HTTPError as error:
        raise GeneratorError(
            f"Could not download {url}: HTTP {error.code} {error.reason}"
        ) from error
    except urllib.error.URLError as error:
        raise GeneratorError(f"Could not download {url}: {error.reason}") from error
    except (socket.timeout, TimeoutError) as error:
        raise GeneratorError(
            f"Could not download {url}: timed out after {DOWNLOAD_TIMEOUT}s"
        ) from error

    if not payload:
        raise GeneratorError(f"Could not download {url}: empty response")
    return payload


def parse_bundle(payload: bytes, origin: str) -> dict[str, Any]:
    """Parse and sanity check the STIX bundle."""
    try:
        bundle = json.loads(payload)
    except ValueError as error:
        raise GeneratorError(f"{origin} is not valid JSON: {error}") from error

    if not isinstance(bundle, dict) or not isinstance(bundle.get("objects"), list):
        raise GeneratorError(f"{origin} is not a STIX bundle (no 'objects' array)")
    if not bundle["objects"]:
        raise GeneratorError(f"{origin} contains no STIX objects")
    return bundle


def mitre_reference(stix_object: dict[str, Any]) -> dict[str, Any] | None:
    """Return the external reference that carries the ATT&CK id, or None."""
    for reference in stix_object.get("external_references") or []:
        if reference.get("source_name") == "mitre-attack" and reference.get("external_id"):
            return reference
    return None


def attack_url(reference: dict[str, Any], attack_id: str, kind: str) -> str:
    """Canonical attack.mitre.org url, with a trailing slash so links concatenate predictably."""
    url = reference.get("url")
    if not url:
        path = attack_id.replace(".", "/")
        url = f"https://attack.mitre.org/{kind}/{path}"
    return url if url.endswith("/") else f"{url}/"


def collect_tactics(bundle: dict[str, Any]) -> dict[str, dict[str, str]]:
    """Map the kill chain phase shortname used by techniques to the tactic it refers to."""
    tactics: dict[str, dict[str, str]] = {}
    for stix_object in bundle["objects"]:
        if stix_object.get("type") != "x-mitre-tactic" or stix_object.get("revoked"):
            continue
        reference = mitre_reference(stix_object)
        shortname = stix_object.get("x_mitre_shortname")
        if not reference or not shortname:
            continue
        tactics[shortname] = {
            "id": reference["external_id"],
            "name": stix_object.get("name", reference["external_id"]),
            "reference": attack_url(reference, reference["external_id"], "tactics"),
        }
    if not tactics:
        raise GeneratorError("No ATT&CK tactics found in the bundle")
    return tactics


def collect_relationships(bundle: dict[str, Any]) -> tuple[dict[str, str], dict[str, str]]:
    """Return (revoked-by, subtechnique-of) maps, both keyed by STIX id."""
    revoked_by: dict[str, str] = {}
    parent_of: dict[str, str] = {}
    for stix_object in bundle["objects"]:
        if stix_object.get("type") != "relationship":
            continue
        kind = stix_object.get("relationship_type")
        source = stix_object.get("source_ref")
        target = stix_object.get("target_ref")
        if not source or not target:
            continue
        if kind == "revoked-by":
            revoked_by[source] = target
        elif kind == "subtechnique-of":
            parent_of[source] = target
    return revoked_by, parent_of


def build(bundle: dict[str, Any], url: str, domain: str) -> dict[str, Any]:
    """Turn the STIX bundle into the RedELK dictionary."""
    tactics_by_shortname = collect_tactics(bundle)
    revoked_by, parent_of = collect_relationships(bundle)

    by_stix_id = {o["id"]: o for o in bundle["objects"] if "id" in o}
    attack_id_of = {}
    for stix_id, stix_object in by_stix_id.items():
        if stix_object.get("type") != "attack-pattern":
            continue
        reference = mitre_reference(stix_object)
        if reference:
            attack_id_of[stix_id] = reference["external_id"]

    techniques: dict[str, dict[str, Any]] = {}
    unknown_phases: set[str] = set()

    for stix_id, attack_id in attack_id_of.items():
        stix_object = by_stix_id[stix_id]
        if domain not in (stix_object.get("x_mitre_domains") or [domain]):
            continue

        tactics = []
        for phase in stix_object.get("kill_chain_phases") or []:
            if phase.get("kill_chain_name") != "mitre-attack":
                continue
            tactic = tactics_by_shortname.get(phase.get("phase_name"))
            if tactic is None:
                unknown_phases.add(str(phase.get("phase_name")))
                continue
            if tactic not in tactics:
                tactics.append(tactic)

        is_subtechnique = bool(stix_object.get("x_mitre_is_subtechnique"))
        parent = attack_id_of.get(parent_of.get(stix_id, ""))
        if parent is None and is_subtechnique and "." in attack_id:
            # Older bundles do not always carry the subtechnique-of relationship.
            parent = attack_id.split(".", 1)[0]

        replacement = attack_id_of.get(revoked_by.get(stix_id, ""))
        # A revoked technique without a revoked-by relationship has no replacement to offer, so
        # treat it as deprecated - that at least tells an operator the id is dead.
        deprecated = bool(stix_object.get("x_mitre_deprecated")) or (
            bool(stix_object.get("revoked")) and replacement is None
        )

        entry = {
            "name": stix_object.get("name", attack_id),
            "tactics": tactics,
            "url": attack_url(mitre_reference(stix_object), attack_id, "techniques"),
            "deprecated": deprecated,
            "revoked_by": replacement,
            "is_subtechnique": is_subtechnique,
            "parent": parent,
        }

        existing = techniques.get(attack_id)
        if existing is not None and existing != entry:
            # Two objects claiming the same ATT&CK id: keep the live one.
            if existing["revoked_by"] or existing["deprecated"]:
                techniques[attack_id] = entry
            print(
                f"warning: duplicate definition for {attack_id}, keeping "
                f"'{techniques[attack_id]['name']}'",
                file=sys.stderr,
            )
            continue
        techniques[attack_id] = entry

    if unknown_phases:
        print(
            f"warning: {len(unknown_phases)} kill chain phase(s) without a tactic object: "
            f"{', '.join(sorted(unknown_phases))}",
            file=sys.stderr,
        )

    bad_ids = sorted(t for t in techniques if not TECHNIQUE_ID.match(t))
    if bad_ids:
        print(f"warning: unexpected technique id format: {', '.join(bad_ids)}", file=sys.stderr)

    collection = next(
        (o for o in bundle["objects"] if o.get("type") == "x-mitre-collection"),
        {},
    )

    return {
        "_generated_by": GENERATED_BY,
        "version": collection.get("x_mitre_version", "unknown"),
        "attack_spec_version": collection.get("x_mitre_attack_spec_version", "unknown"),
        "domain": domain,
        "source": url,
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "counts": {
            "techniques": sum(1 for t in techniques.values() if not t["is_subtechnique"]),
            "subtechniques": sum(1 for t in techniques.values() if t["is_subtechnique"]),
            "revoked": sum(1 for t in techniques.values() if t["revoked_by"]),
            "deprecated": sum(1 for t in techniques.values() if t["deprecated"]),
        },
        "techniques": techniques,
    }


def serialise(dictionary: dict[str, Any]) -> str:
    """One line per technique: small enough to ship, still readable in a diff."""
    head = {key: value for key, value in dictionary.items() if key != "techniques"}
    lines = json.dumps(head, indent=1, sort_keys=True).split("\n")[1:-1]
    lines[-1] += ","
    lines.append(' "techniques": {')
    entries = [
        f"  {json.dumps(attack_id)}: {json.dumps(dictionary['techniques'][attack_id], sort_keys=True)}"
        for attack_id in sorted(dictionary["techniques"])
    ]
    lines.append(",\n".join(entries))
    lines.append(" }")
    return "{\n" + "\n".join(lines) + "\n}\n"


def unchanged(path: Path, dictionary: dict[str, Any]) -> bool:
    """True when the file already holds this ATT&CK content.

    The generation timestamp is ignored on purpose: it records when the content last changed, so
    that re-running the generator against an unchanged ATT&CK release is a no-op in git.
    """
    if not path.is_file():
        return False
    try:
        current = json.loads(path.read_text(encoding="utf-8"))
    except (ValueError, OSError):
        return False
    volatile = ("generated",)
    return {k: v for k, v in current.items() if k not in volatile} == {
        k: v for k, v in dictionary.items() if k not in volatile
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--url", default=DEFAULT_URL, help="STIX bundle to download")
    parser.add_argument(
        "--input",
        type=Path,
        help="use an already downloaded STIX bundle instead of fetching it",
    )
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT, help="where to write the dictionary"
    )
    parser.add_argument("--domain", default=DEFAULT_DOMAIN, help="ATT&CK domain to extract")
    parser.add_argument(
        "--force", action="store_true", help="rewrite even when the content is unchanged"
    )
    args = parser.parse_args(argv)

    try:
        if args.input:
            if not args.input.is_file():
                raise GeneratorError(f"{args.input} does not exist")
            payload = args.input.read_bytes()
            origin = str(args.input)
        else:
            print(f"Downloading {args.url}", file=sys.stderr)
            payload = download(args.url)
            origin = args.url

        bundle = parse_bundle(payload, origin)
        dictionary = build(bundle, args.url, args.domain)

        if not dictionary["techniques"]:
            raise GeneratorError(f"{origin} contains no techniques for domain {args.domain}")

        if not args.force and unchanged(args.output, dictionary):
            print(f"{args.output} is already up to date (ATT&CK {dictionary['version']})")
            return 0

        args.output.parent.mkdir(parents=True, exist_ok=True)
        tmp = args.output.with_suffix(args.output.suffix + ".tmp")
        tmp.write_text(serialise(dictionary), encoding="utf-8")
        os.replace(tmp, args.output)
    except GeneratorError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    counts = dictionary["counts"]
    print(
        f"Wrote {args.output} - ATT&CK {dictionary['version']} "
        f"(spec {dictionary['attack_spec_version']}): "
        f"{counts['techniques']} techniques, {counts['subtechniques']} sub-techniques, "
        f"{counts['revoked']} revoked, {counts['deprecated']} deprecated"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
