name: Lint - Python

on:
  push:
    paths:
      - "elkserver/docker/redelk-base/redelkinstalldata/scripts/**"
      - .github/workflows/lint.yml
  pull_request:
    paths:
      - "elkserver/docker/redelk-base/redelkinstalldata/scripts/**"
      - .github/workflows/lint.yml

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check files using black formatter
        uses: datadog/action-py-black-formatter@v2.5
        with:
          check_mode: false
          additional_args: "-t py36 elkserver/docker/redelk-base/redelkinstalldata/scripts"

      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "style: autoformatted code with black"
          branch: "develop"
